name: scheduled_work_flow

on: 
 push: 
  branches: 
   - main
jobs:
 today_tasks: 
  runs-on: ubuntu-latest

  steps: 
  - name: print good morning
    run: echo "Good Morninng champion"

  - name: show current time
    run: |
      echo "Current UTC time: $(date -u)"
      echo "Current local time: $(date)"
